# BAB 1 — API ELEMENTS OF SCIKIT-LEARN

## 1.1 Pengenalan Scikit-Learn

Scikit-learn adalah library Python yang digunakan untuk membuat model Machine Learning.

Scikit-learn menyediakan berbagai fitur seperti:
- Klasifikasi
- Regresi
- Clustering
- Preprocessing data
- Dimensionality Reduction
- Evaluasi model

Secara umum, proses Machine Learning menggunakan scikit-learn adalah:

Data → Preprocessing → Training → Prediksi → Evaluasi

Beberapa konsep penting dalam scikit-learn:
- Estimator → model yang dapat belajar dari data
- Transformer → digunakan untuk mengubah atau memproses data
- Pipeline → menggabungkan beberapa proses menjadi satu alur
- fit() → mempelajari data
- transform() → mengubah data
- predict() → menghasilkan prediksi

## 1.2 Import Library

Library yang digunakan pada bab ini adalah NumPy, Pandas, dan beberapa modul dari Scikit-Learn.

NumPy digunakan untuk melakukan operasi numerik dan membuat array.

Pandas digunakan untuk mengolah data dalam bentuk tabel atau DataFrame.

Scikit-Learn digunakan untuk membuat model Machine Learning, membagi data, dan melakukan preprocessing.

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

## 1.3 Estimator

Estimator adalah objek dalam scikit-learn yang digunakan untuk mempelajari pola dari data.

Contohnya adalah LinearRegression yang digunakan untuk membuat model regresi linear.

Model dibuat terlebih dahulu menggunakan LinearRegression().
Pada tahap ini model belum belajar dari data.

Model baru akan belajar setelah menggunakan method fit().

In [2]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

### Melatih Model dengan fit()

Method fit() digunakan untuk melatih model menggunakan data.

Pada contoh berikut:
- X merupakan data input atau fitur
- y merupakan target yang ingin diprediksi

Setelah fit() dijalankan, model akan mempelajari hubungan antara X dan y.

In [3]:
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([2, 4, 6, 8, 10])

model.fit(X, y)

LinearRegression()

## 1.4 Melakukan Prediksi

Setelah model selesai dilatih, kita dapat menggunakan method predict() untuk menghasilkan prediksi.

Pada contoh ini, model diberikan nilai 6 dan akan mencoba memprediksi nilai target berdasarkan pola yang telah dipelajari.

In [4]:
prediksi = model.predict([[6]])

print("Hasil prediksi:", prediksi)

Hasil prediksi: [12.]


Model mempelajari pola:

1 → 2
2 → 4
3 → 6
4 → 8
5 → 10

Sehingga untuk input 6, model akan menghasilkan prediksi yang mendekati 12.

## 1.5 Training Data dan Testing Data

Data biasanya dibagi menjadi dua bagian:

1. Training Data
   Digunakan untuk melatih model.

2. Testing Data
   Digunakan untuk menguji kemampuan model pada data yang belum digunakan saat training.

Pembagian data dapat dilakukan menggunakan train_test_split().

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X Train:", X_train)
print("X Test:", X_test)

X Train: [[5]
 [3]
 [1]
 [4]]
X Test: [[2]]


Parameter test_size=0.2 berarti sekitar 20% data digunakan sebagai data testing.

Parameter random_state digunakan agar pembagian data tetap sama setiap kali kode dijalankan.

## 1.6 Transformer

Transformer adalah objek yang digunakan untuk melakukan transformasi atau preprocessing pada data.

Salah satu contoh transformer adalah StandardScaler.

StandardScaler digunakan untuk melakukan standardisasi sehingga skala data menjadi lebih seimbang.

Transformer biasanya memiliki method:
- fit() → mempelajari karakteristik data
- transform() → melakukan transformasi data
- fit_transform() → melakukan fit() dan transform() sekaligus

In [6]:
from sklearn.preprocessing import StandardScaler

X = np.array([
    [10],
    [20],
    [30],
    [40],
    [50]
])

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


## 1.7 fit(), transform(), dan fit_transform()

Pada transformer terdapat tiga method yang sering digunakan.

fit()
Digunakan untuk mempelajari informasi dari data.

transform()
Digunakan untuk mengubah data berdasarkan informasi yang telah dipelajari.

fit_transform()
Merupakan gabungan dari fit() dan transform().

Secara sederhana:

fit() → belajar
transform() → mengubah data
fit_transform() → belajar + mengubah data

In [7]:
scaler = StandardScaler()

scaler.fit(X)

X_scaled = scaler.transform(X)

print(X_scaled)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [8]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


## 1.8 Pipeline

Pipeline digunakan untuk menggabungkan beberapa proses Machine Learning menjadi satu alur.

Contohnya:

Data
↓
Scaling
↓
Model
↓
Prediksi

Dengan Pipeline, proses preprocessing dan training dapat dilakukan secara lebih rapi dan terstruktur.

Pipeline juga membantu mengurangi kesalahan karena preprocessing dan model disimpan dalam satu objek.

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression())
])

### Contoh Pipeline

Pada contoh berikut digunakan dataset Iris.

Data akan melalui proses:
1. StandardScaler
2. Logistic Regression
3. Prediksi

Semua proses tersebut dijalankan melalui satu Pipeline.

In [10]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()

X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

pipeline.fit(X_train, y_train)

accuracy = pipeline.score(X_test, y_test)

print("Akurasi:", accuracy)

Akurasi: 1.0


## 1.9 Kesimpulan Bab 1

Pada bab ini telah dipelajari dasar penggunaan API pada scikit-learn.

Estimator
→ Model yang dapat belajar dari data.

fit()
→ Digunakan untuk melatih atau mempelajari data.

predict()
→ Digunakan untuk menghasilkan prediksi.

Transformer
→ Digunakan untuk melakukan transformasi atau preprocessing.

transform()
→ Mengubah data berdasarkan hasil pembelajaran.

Pipeline
→ Menggabungkan beberapa proses preprocessing dan model menjadi satu alur.

Alur sederhananya:

Data → Preprocessing → Training → Prediction → Evaluation