# BAB 6 — ADVANCED LOGISTIC REGRESSION

## 6.1 Pengenalan Logistic Regression

Logistic Regression merupakan algoritma Machine Learning yang digunakan untuk klasifikasi.

Berbeda dengan Linear Regression yang menghasilkan nilai kontinu, Logistic Regression menghasilkan probabilitas suatu data masuk ke kelas tertentu.

Contohnya:
- Spam atau bukan spam
- Sakit atau sehat
- Lulus atau tidak lulus
- Cancel atau tidak cancel

Logistic Regression dapat digunakan untuk binary classification maupun multiclass classification.

## 6.2 Binary Classification

Binary Classification adalah klasifikasi yang hanya memiliki dua kelas.

Contohnya:

0 → Tidak Lulus
1 → Lulus

Pada contoh berikut digunakan dataset Breast Cancer dari scikit-learn.

In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

data = load_breast_cancer()

X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model = Pipeline([
    ("scaler", StandardScaler()),
    ("logistic", LogisticRegression(max_iter=1000))
])

model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)

print("Akurasi:", accuracy)

Akurasi: 0.9824561403508771


## 6.3 Probabilitas Prediksi

Selain menghasilkan kelas, Logistic Regression juga dapat menghasilkan probabilitas menggunakan predict_proba().

Hasil probabilitas menunjukkan seberapa besar kemungkinan data termasuk ke masing-masing kelas.

In [2]:
probability = model.predict_proba(X_test)

print(probability[:5])

[[9.99999941e-01 5.88824186e-08]
 [1.13351672e-05 9.99988665e-01]
 [9.93589175e-01 6.41082462e-03]
 [4.66491463e-01 5.33508537e-01]
 [9.99999999e-01 6.52500097e-10]]


Pada hasil tersebut, setiap baris menunjukkan probabilitas untuk masing-masing kelas.

Jumlah probabilitas pada setiap baris adalah 1.

## 6.4 Mengubah Threshold

Secara default, Logistic Regression menggunakan threshold sekitar 0.5 untuk menentukan kelas.

Jika probabilitas kelas positif >= 0.5, data dapat dikategorikan sebagai kelas 1.

Threshold dapat diubah sesuai kebutuhan.

Contohnya, threshold 0.7 akan membuat model lebih ketat dalam memberikan prediksi kelas positif.

In [3]:
import numpy as np

probability = model.predict_proba(X_test)[:, 1]

threshold = 0.7

y_pred_custom = (probability >= threshold).astype(int)

print(y_pred_custom[:20])

[0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 1]


## 6.5 Multiclass Classification

Multiclass Classification adalah klasifikasi yang memiliki lebih dari dua kelas.

Contohnya dataset Iris memiliki tiga kelas:

0 → Setosa
1 → Versicolor
2 → Virginica

Logistic Regression dapat digunakan untuk melakukan multiclass classification.

In [4]:
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model_multi = Pipeline([
    ("scaler", StandardScaler()),
    ("logistic", LogisticRegression(max_iter=1000))
])

model_multi.fit(X_train, y_train)

print(
    "Akurasi:",
    model_multi.score(X_test, y_test)
)

Akurasi: 0.9333333333333333


## 6.6 Regularization pada Logistic Regression

Logistic Regression juga menggunakan regularization untuk membantu mengontrol kompleksitas model.

Parameter C mengatur kekuatan regularization.

Nilai C kecil
→ regularization lebih kuat.

Nilai C besar
→ regularization lebih lemah.

Pada scikit-learn, regularization default LogisticRegression menggunakan L2.

In [5]:
for C in [0.01, 0.1, 1, 10, 100]:

    model = Pipeline([
        ("scaler", StandardScaler()),
        ("logistic", LogisticRegression(
            C=C,
            max_iter=1000
        ))
    ])

    model.fit(X_train, y_train)

    accuracy = model.score(
        X_test,
        y_test
    )

    print(
        "C =", C,
        "| Akurasi =", accuracy
    )

C = 0.01 | Akurasi = 0.8
C = 0.1 | Akurasi = 0.8666666666666667
C = 1 | Akurasi = 0.9333333333333333
C = 10 | Akurasi = 1.0
C = 100 | Akurasi = 1.0


## 6.7 Confusion Matrix

Confusion Matrix digunakan untuk melihat hasil klasifikasi secara lebih detail.

Confusion Matrix terdiri dari:

True Positive
→ Prediksi positif dan kenyataannya positif.

True Negative
→ Prediksi negatif dan kenyataannya negatif.

False Positive
→ Diprediksi positif tetapi sebenarnya negatif.

False Negative
→ Diprediksi negatif tetapi sebenarnya positif.

In [6]:
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)

cm = confusion_matrix(
    y_test,
    y_pred
)

print(cm)

[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


## 6.8 ROC Curve

ROC Curve digunakan untuk melihat kemampuan model dalam membedakan kelas positif dan negatif pada berbagai threshold.

ROC menggunakan:
- True Positive Rate
- False Positive Rate

AUC atau Area Under the Curve menunjukkan luas area di bawah ROC Curve.

Semakin dekat nilai AUC ke 1, semakin baik kemampuan model dalam membedakan kelas pada data evaluasi tersebut.

## 6.9 Kesimpulan Bab 6

Logistic Regression
→ Digunakan untuk klasifikasi.

Binary Classification
→ Memiliki dua kelas.

Multiclass Classification
→ Memiliki lebih dari dua kelas.

predict_proba()
→ Menghasilkan probabilitas prediksi.

Threshold
→ Menentukan batas probabilitas untuk klasifikasi.

Regularization
→ Membantu mengontrol kompleksitas model.

Confusion Matrix
→ Menunjukkan hasil prediksi secara detail.

ROC Curve
→ Menunjukkan kemampuan model pada berbagai threshold.

AUC
→ Mengukur area di bawah ROC Curve.